Задача по имитации отправки запроса на сервер
Mr-Ali777/Homework pull request #5
Opened 2024-09-25 13:09 UTC by Mr-Ali777

2024-09-27 20:33 UTC, Mr-Ali777 commented
В задаче по Квиз есть ошибка, не могу понять причину.

2024-10-02 23:44 UTC, nikitapt63 approved these changes

2024-10-02 23:44 UTC, nikitapt63 commented on Home _work/Education_django_HW/course/models.py
> +    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
Стоит связать курс с автором, а не  наоборот. Гораздо удобнее выбирать автора при создании курса, а не при создании автора выбирать его курсы.

2024-10-02 23:46 UTC, nikitapt63 requested changes

2024-10-02 23:46 UTC, nikitapt63 commented on Home _work/Education_django_HW/course/models.py
> +    course_author = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
Стоит связать курс с автором, а не наоборот. Гораздо удобнее выбирать автора при создании курса, а не при создании автора выбирать его курсы.

2024-10-05 15:00 UTC, nikitapt63 approved these changes

2024-10-07 14:40 UTC, merged